<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="2" buildNumber="2438" updateStamp="_l0x7C2qnEeGMCd15vaZIXw" externalChecksum="3054974779:507989954" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//idType">
        <dataTypeName manuallyCreated="true" value="idType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section001'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section002'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section003'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section004'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section005'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section006'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section007'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section008'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section009'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Section0010'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//favoriteGameshowType">
        <dataTypeName manuallyCreated="true" value="favoriteGameshowType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Jeopardy'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Wheel of Fortune'"/>
        </enumerationElements>
      </customDataTypeList>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Part"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//idType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="seq"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Individual">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Individual"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1" eType="#//Part">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="part"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qtyGuns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="qtyGuns"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dob" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dob"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beenArrested" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="beenArrested"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ableToSpeak" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ableToSpeak"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qtyBedrooms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="qtyBedrooms"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="favoriteGameshow" eType="#//favoriteGameshowType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="favoriteGameshow"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="liveinDC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="liveinDC"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="idType">
    <eLiterals name="V0" literal="'Section001'"/>
    <eLiterals name="V1" value="1" literal="'Section002'"/>
    <eLiterals name="V2" value="2" literal="'Section003'"/>
    <eLiterals name="V3" value="3" literal="'Section004'"/>
    <eLiterals name="V4" value="4" literal="'Section005'"/>
    <eLiterals name="V5" value="5" literal="'Section006'"/>
    <eLiterals name="V6" value="6" literal="'Section007'"/>
    <eLiterals name="V7" value="7" literal="'Section008'"/>
    <eLiterals name="V8" value="8" literal="'Section009'"/>
    <eLiterals name="V9" value="9" literal="'Section0010'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="favoriteGameshowType">
    <eLiterals name="V0" literal="'Jeopardy'"/>
    <eLiterals name="V1" value="1" literal="'Wheel of Fortune'"/>
  </eClassifiers>
</ecore:EPackage>
