<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="2" buildNumber="2438" updateStamp="_k6UdoGqnEeGMCd15vaZIXw" externalChecksum="3054974779:507989954" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//maritalStatusType">
        <dataTypeName manuallyCreated="true" value="maritalStatusType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Single'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Married'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Divorced'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Widow'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//statusType">
        <dataTypeName manuallyCreated="true" value="statusType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Silver'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Gold'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Diamond'"/>
        </enumerationElements>
      </customDataTypeList>
      <databaseMetadata>
        <tableMetadataList catalogName="Documents" schemaName="corticon" tableName="CUSTOMER">
          <columnMetadataList columnName="AGE" jdbcDataType="BIGINT" sqlDataType="bigint" columnSize="19"/>
          <columnMetadataList columnName="MARITALSTATUS" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="NAME" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="REQUESTAMOUNT" jdbcDataType="DECIMAL" sqlDataType="decimal" columnSize="19" decimalDigits="2"/>
          <columnMetadataList columnName="REQUESTTYPE" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="SSN" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="STATE" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="STATUS" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <columnMetadataList columnName="ZIP" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <primaryKeyMetadataList primaryKeyName="CUSTOMER_PK" primaryKeyCatalogName="Documents" primaryKeySchemaName="corticon" primaryKeyTableName="CUSTOMER"/>
        </tableMetadataList>
        <tableMetadataList catalogName="Documents" schemaName="corticon" tableName="DOCUMENT">
          <columnMetadataList columnName="ID" jdbcDataType="BIGINT" sqlDataType="bigint" columnSize="19"/>
          <columnMetadataList columnName="NAME" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <primaryKeyMetadataList primaryKeyName="DOCUMENT_PK" primaryKeyCatalogName="Documents" primaryKeySchemaName="corticon" primaryKeyTableName="DOCUMENT"/>
          <foreignKeyMetadataList foreignKeyName="DOCUMENT_PARAGRAPH_FK1" foreignKeyCatalogName="Documents" foreignKeySchemaName="corticon" foreignKeyTableName="DOCUMENT_PARAGRAPH"/>
        </tableMetadataList>
        <tableMetadataList catalogName="Documents" schemaName="corticon" tableName="DOCUMENT_PARAGRAPH">
          <columnMetadataList columnName="FK_DOCUMENT_ID" jdbcDataType="BIGINT" sqlDataType="bigint" columnSize="19"/>
          <columnMetadataList columnName="FK_PARAGRAPH_ID" jdbcDataType="BIGINT" sqlDataType="bigint" columnSize="19"/>
          <primaryKeyMetadataList primaryKeyName="DOCUMENT_PARAGRAPH_PK" primaryKeyCatalogName="Documents" primaryKeySchemaName="corticon" primaryKeyTableName="DOCUMENT_PARAGRAPH"/>
        </tableMetadataList>
        <tableMetadataList catalogName="Documents" schemaName="corticon" tableName="PARAGRAPH">
          <columnMetadataList columnName="ID" jdbcDataType="BIGINT" sqlDataType="bigint" columnSize="19"/>
          <columnMetadataList columnName="TEXT" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="256"/>
          <primaryKeyMetadataList primaryKeyName="PARAGRAPH_PK" primaryKeyCatalogName="Documents" primaryKeySchemaName="corticon" primaryKeyTableName="PARAGRAPH"/>
          <foreignKeyMetadataList foreignKeyName="DOCUMENT_PARAGRAPH_FK2" foreignKeyCatalogName="Documents" foreignKeySchemaName="corticon" foreignKeyTableName="DOCUMENT_PARAGRAPH"/>
        </tableMetadataList>
        <tableMetadataList catalogName="Documents" schemaName="dbo" tableName="dtproperties">
          <columnMetadataList columnName="id" jdbcDataType="INTEGER" sqlDataType="int identity" columnSize="10"/>
          <columnMetadataList columnName="lvalue" jdbcDataType="LONGVARBINARY" sqlDataType="image" columnSize="2147483647"/>
          <columnMetadataList columnName="objectid" jdbcDataType="INTEGER" sqlDataType="int" columnSize="10"/>
          <columnMetadataList columnName="property" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="64"/>
          <columnMetadataList columnName="uvalue" jdbcDataType="VARCHAR" sqlDataType="nvarchar" columnSize="255"/>
          <columnMetadataList columnName="value" jdbcDataType="VARCHAR" sqlDataType="varchar" columnSize="255"/>
          <columnMetadataList columnName="version" jdbcDataType="INTEGER" sqlDataType="int" columnSize="10"/>
          <primaryKeyMetadataList primaryKeyName="pk_dtproperties" primaryKeyCatalogName="Documents" primaryKeySchemaName="dbo" primaryKeyTableName="dtproperties"/>
        </tableMetadataList>
      </databaseMetadata>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Document"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paragraph" upperBound="-1" eType="#//Paragraph">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="paragraph"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Paragraph"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="text"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Customer"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="age"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="zip"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="requestType"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="requestAmount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maritalStatus" eType="#//maritalStatusType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="maritalStatus"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ssn"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="state"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//statusType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="status"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="maritalStatusType">
    <eLiterals name="V0" literal="'Single'"/>
    <eLiterals name="V1" value="1" literal="'Married'"/>
    <eLiterals name="V2" value="2" literal="'Divorced'"/>
    <eLiterals name="V3" value="3" literal="'Widow'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="statusType">
    <eLiterals name="V0" literal="'Silver'"/>
    <eLiterals name="V1" value="1" literal="'Gold'"/>
    <eLiterals name="V2" value="2" literal="'Diamond'"/>
  </eClassifiers>
</ecore:EPackage>
