<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="2" buildNumber="2438" updateStamp="_kiksAGqnEeGMCd15vaZIXw" externalChecksum="3054974779:507989954" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//homeStateType">
        <dataTypeName manuallyCreated="true" value="homeStateType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'CA'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'AZ'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'NV'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//riskRatingType">
        <dataTypeName manuallyCreated="true" value="riskRatingType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'High'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Low'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//maritalStatusType">
        <dataTypeName manuallyCreated="true" value="maritalStatusType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'married'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'single'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//genderType">
        <dataTypeName manuallyCreated="true" value="genderType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'male'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'female'"/>
        </enumerationElements>
      </customDataTypeList>
      <databaseMetadata>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="APPLICANT">
          <columnMetadataList columnName="AGE" jdbcDataType="INTEGER" sqlDataType="INT" columnSize="10"/>
          <columnMetadataList columnName="GENDER" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="HOMESTATE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="MARITALSTATUS" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="NAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="RISKRATING" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="SKYDIVER" jdbcDataType="BIT" sqlDataType="BIT" columnSize="1"/>
          <columnMetadataList columnName="SSN" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_APPLICANT" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="APPLICANT"/>
          <foreignKeyMetadataList foreignKeyName="FK_POLICY_APPLICANT" foreignKeyCatalogName="SKYDIVER" foreignKeySchemaName="DBO" foreignKeyTableName="POLICY"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="DTPROPERTIES">
          <columnMetadataList columnName="ID" jdbcDataType="INTEGER" sqlDataType="INT IDENTITY" columnSize="10"/>
          <columnMetadataList columnName="LVALUE" jdbcDataType="LONGVARBINARY" sqlDataType="IMAGE" columnSize="2147483647"/>
          <columnMetadataList columnName="OBJECTID" jdbcDataType="INTEGER" sqlDataType="INT" columnSize="10"/>
          <columnMetadataList columnName="PROPERTY" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="64"/>
          <columnMetadataList columnName="UVALUE" jdbcDataType="VARCHAR" sqlDataType="NVARCHAR" columnSize="255"/>
          <columnMetadataList columnName="VALUE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="255"/>
          <columnMetadataList columnName="VERSION" jdbcDataType="INTEGER" sqlDataType="INT" columnSize="10"/>
          <primaryKeyMetadataList primaryKeyName="PK_DTPROPERTIES" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="DTPROPERTIES"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="JPOX_TABLES">
          <columnMetadataList columnName="CLASS_NAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="128"/>
          <columnMetadataList columnName="OWNER" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="2"/>
          <columnMetadataList columnName="TABLE_NAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="128"/>
          <columnMetadataList columnName="TYPE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="4"/>
          <columnMetadataList columnName="VERSION" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="20"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="PARAMDATATYPES">
          <columnMetadataList columnName="PARAMDATATYPENAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_PARAMDATATYPES" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="PARAMDATATYPES"/>
          <foreignKeyMetadataList foreignKeyName="FK_PARAMETERS_PARAMDATATYPES" foreignKeyCatalogName="SKYDIVER" foreignKeySchemaName="DBO" foreignKeyTableName="PARAMDEFINITIONS"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="PARAMDEFINITIONS">
          <columnMetadataList columnName="EXTENDSTABLE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="ID" jdbcDataType="INTEGER" sqlDataType="INT IDENTITY" columnSize="10"/>
          <columnMetadataList columnName="PARAMDATATYPE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="PARAMNAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_PARAMETERS" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="PARAMDEFINITIONS"/>
          <foreignKeyMetadataList foreignKeyName="FK_PARAMVALUES_PARAMDEFINITIONS" foreignKeyCatalogName="SKYDIVER" foreignKeySchemaName="DBO" foreignKeyTableName="PARAMVALUES"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="PARAMVALUES">
          <columnMetadataList columnName="ID" jdbcDataType="INTEGER" sqlDataType="INT IDENTITY" columnSize="10"/>
          <columnMetadataList columnName="PARAMDEFID" jdbcDataType="INTEGER" sqlDataType="INT" columnSize="10"/>
          <columnMetadataList columnName="PARAMVALUE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="REFERSTORECID" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_PARAMS" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="PARAMVALUES"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="POLICY">
          <columnMetadataList columnName="EFFECTIVEDATE" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="ENDDATE" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="ID" jdbcDataType="INTEGER" sqlDataType="INT IDENTITY" columnSize="10"/>
          <columnMetadataList columnName="PREMIUM" jdbcDataType="DECIMAL" sqlDataType="DECIMAL" columnSize="18"/>
          <columnMetadataList columnName="SPECIALCOVERAGE" jdbcDataType="BIT" sqlDataType="BIT" columnSize="1"/>
          <columnMetadataList columnName="SSN" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_POLICY" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="POLICY"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="RATINGTYPES">
          <columnMetadataList columnName="NAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
        </tableMetadataList>
        <tableMetadataList catalogName="SKYDIVER" schemaName="DBO" tableName="RULEMESSAGES">
          <columnMetadataList columnName="DS_EFFECT_DATE" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="DS_EXPIR_DATE" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="DS_NAME" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="DS_VERSION_LABEL" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="DS_VERSION_NO" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="ID" jdbcDataType="INTEGER" sqlDataType="INT IDENTITY" columnSize="10"/>
          <columnMetadataList columnName="MESSAGE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="255"/>
          <columnMetadataList columnName="REF_RECORD_ID" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="REF_TABLE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="100"/>
          <columnMetadataList columnName="RQ_EFFECT_TS" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="RQ_TARGET_VERSION_NO" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <columnMetadataList columnName="RQ_TS" jdbcDataType="TIMESTAMP" sqlDataType="DATETIME" columnSize="23" decimalDigits="3"/>
          <columnMetadataList columnName="RS_FILE" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="255"/>
          <columnMetadataList columnName="SEV" jdbcDataType="VARCHAR" sqlDataType="VARCHAR" columnSize="50"/>
          <primaryKeyMetadataList primaryKeyName="PK_RULEMESSAGES" primaryKeyCatalogName="SKYDIVER" primaryKeySchemaName="DBO" primaryKeyTableName="RULEMESSAGES"/>
        </tableMetadataList>
      </databaseMetadata>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Beneficiary">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Beneficiary"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationship" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="relationship"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="percentage"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Applicant">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Applicant"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" upperBound="-1" eType="#//Policy">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="policy"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1" eType="#//Comment">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="comment"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ssn"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeState" eType="#//homeStateType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="homeState"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="riskRating" eType="#//riskRatingType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="riskRating"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maritalStatus" eType="#//maritalStatusType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.2">
          <name manuallyCreated="true" value="maritalStatus"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//genderType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="gender"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="age"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skydiver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="skydiver"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scenario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="scenario"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Comment"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="text"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Policy"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beneficiary" upperBound="-1" eType="#//Beneficiary">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="beneficiary"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="premium" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="premium"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="effectiveDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="endDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialCoverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="specialCoverage"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="homeStateType">
    <eLiterals name="V0" literal="'CA'"/>
    <eLiterals name="V1" value="1" literal="'AZ'"/>
    <eLiterals name="V2" value="2" literal="'NV'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="riskRatingType">
    <eLiterals name="V0" literal="'High'"/>
    <eLiterals name="V1" value="1" literal="'Low'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="maritalStatusType">
    <eLiterals name="V0" literal="'married'"/>
    <eLiterals name="V1" value="1" literal="'single'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="genderType">
    <eLiterals name="V0" literal="'male'"/>
    <eLiterals name="V1" value="1" literal="'female'"/>
  </eClassifiers>
</ecore:EPackage>
