<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="3" majorServiceNumber="3" buildNumber="5565" updateStamp="_XvSVEGhLEeOwx4C8AWaqWA" externalChecksum="3054974779:507989954" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Trace"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ruleList"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rulesheets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="rulesheets"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shape">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Shape"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Thing"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="color"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="size"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="shape"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="price"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="expectedPrice"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="status"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1" eType="#//Attachment">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="attachments"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Color"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DEBUG">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="DEBUG"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThingSize">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="ThingSize"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Attachment"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="color"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
